### PR TITLE
Fix nest thermostat page

### LINKED ISSUE #33: Nest thermostat screen is blank
image

This shouldn't be a data issue.  The tile on the dashboard is correct and using the same data as the thermostat screen:

image

As an aside...  The Nest thermostat component could be redesigned to be more agnostic about the kind of thermostat.

For inspiration:
image

### PR DESCRIPTION
**Pull request by grgur**
closes #33

### CODE REVIEW

File: src/dev/config.js [hunk 1]
```diff
@@ -427,11 +427,11 @@ module.exports = {
 
   nest: {
     // one or more thermostats
-    thermostats: [{ device: "structure/thermostat_name", name: "Hallway Thermostat" }],
+    thermostats: [{ device: "Falsetto/Hallway Thermostat", name: "Hallway Thermostat" }],
```
Comment (mschwartz) [inline src/dev/config.js]: Falsetto/Hallway Thermostat 

That's my home.

Maybe we can go through the dummy data and remove references to my home?

After talking to Andy Dennis and showing him my config.js, he said I am advertising all the electronics I have and my income level and so on.
